### ISSUE TITLE
pymc requires gfortran?

### ISSUE THREAD

**Issue by selseyastro** [pavolgaj/OCFit#7] opened 2019-05-10 16:54 UTC
So I installed gfortran and it is there! In C:/MinGW/bin/gfortran
Now try and install pymc and error is fortran compiler missing???
Said it had Fortran sources but no compiler.

What is going on??

And I was trying to help a fellow astronomer in our team who needs to use Ocfit.

Regards
John

**Comment by pavolgaj** [comment] 2019-05-10 17:13
Duplicate of #6

**Closed as completed by pavolgaj** 2019-05-10 17:13 UTC
Labels: duplicate, help wanted
